version: '3.8'

services:
  mysimulator:
    build: .
    container_name: mysimulator_c
    ports:
      - '3000:3000'
    volumes:
      - .:/app
      - /app/node_modules
    stdin_open: true
    tty: true
